name: Checks Builds on PR

on: [pull_request]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dotnet Build
        run: |
          cd Zeus
          dotnet restore Zeus.csproj
          dotnet build Zeus.csproj --configuration Release

  Test:
    needs: Build
    runs-on: windows-latest
    steps:
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dotnet Build
        run: |
          cd Zeus
          dotnet restore Zeus.csproj
          dotnet build Zeus.csproj --configuration Release
